const USER_ROLE_APPLICANT = 0;
const USER_ROLE_ENROLLEE = 1;
const USER_ROLE_POSTGRAD = 2;
const USER_ROLE_ADMIN = 3;

module.exports = {
    USER_ROLE_ADMIN,
    USER_ROLE_APPLICANT,
    USER_ROLE_ENROLLEE,
    USER_ROLE_POSTGRAD,
};
