export class RegistrationData {
  constructor(
    public firstName: string,
    public surname: string,
    public lastName: string,
    public sex: string,
    public dateOfBirth: string,
    public speciality: number,
    public faculty: string,
    public chair: string,
    public trainingForm: string,
    public payForm: string,
    public languageType: string,
    public university: string,
    public universityYear: string,
    public degreeType: string,
    public degreeHonor: string,
    public email: string,
    public phone: string,
    public publishCount: number,
    public averageMark: number,
    public indicia: string,
    public supervisor: string,
    public additionalInfo: string,
    public hostel: boolean,
  ) {}

  public static toDatabaseData(data: RegistrationData): any {
    return {
      first_name: data.firstName,
      middle_name: data.surname,
      last_name: data.lastName,
      sex: data.sex,
      data_of_birth: data.dateOfBirth,
      speciality: data.speciality,
      faculty: data.faculty,
      department: data.chair,
      training_form: data.trainingForm,
      pay_form: data.payForm,
      language_type: data.languageType,
      university: data.university,
      university_year: data.universityYear,
      degree_type: data.degreeType,
      degree_honor: data.degreeHonor,
      email: data.email,
      phone: data.phone,
      additional_info: data.additionalInfo,
      publish_count: `${data.publishCount}`,
      average_mark: data.averageMark,
      supervisor: data.supervisor,
      indicia: data.indicia,
      hostel: data.hostel,
      create_date: Date.now(),
    };
  }
}
